post http://localhost:4600/user/register
Content-Type: application/json

{
    "userName":"Michael Otieno",
    "email":"mikevenum9@gmail.com",
    "password":"379226",
    "phone_no":"0703142454"
}


###
#login user
POST http://localhost:4600/user/login
Content-Type: application/json

{
    "email":"michealvenum007@gmail.com",
    "password":"379226"

}


###
#get all user

get http://localhost:4600/user/
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI3MWU0OWQ3Mi0yNjIyLTRiZWItOTQxYy1kMDZiZGJkZjhkMzciLCJ1c2VyTmFtZSI6Ik1pY2hhZWwgT3RpZW5vIiwiZW1haWwiOiJtaWNoZWFsdmVudW0wMDdAZ21haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2UsIkFzc2lnbmVkUHJvamVjdElEIjpudWxsLCJFbWFpbFNlbnQiOmZhbHNlLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2OTg4NDg4ODEsImV4cCI6MTY5ODg1MjQ4MX0.wopU80FomBiJMyfNSTX6leJTiu7nw6Ud3ZGi_7MJst0


###
#check user details
GET http://localhost:4600/user/check_user_details
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI3MWU0OWQ3Mi0yNjIyLTRiZWItOTQxYy1kMDZiZGJkZjhkMzciLCJ1c2VyTmFtZSI6Ik1pY2hhZWwgT3RpZW5vIiwiZW1haWwiOiJtaWNoZWFsdmVudW0wMDdAZ21haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2UsIkFzc2lnbmVkUHJvamVjdElEIjpudWxsLCJFbWFpbFNlbnQiOmZhbHNlLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2OTg4NzU0NTIsImV4cCI6MTY5ODg3OTA1Mn0.qsQi-r_jZVoAihToyO2HRNOOEZttROjDuBWIm1-lofA



###
#admin assign project

POST http://localhost:4600/project/assignProject
Content-Type: application/json

{
   
    "projectName": "BackgroundSerices",
    "projectDescription": "build company chatbot",
    "endDate": "2023-11-9",
    "AssignedUserEmail": "cylvonnen@gmail.com",  
    "AssignedUserName": "Joshua Ochieng"  
}

###
#delete project
DELETE  http://localhost:4600/project/deleteProject
Content-Type: application/json

{
   
    "projectID":"cffec93f-cf3f-4fcc-a69d-67825c63548c"
   
}


###
#get all projects
get  http://localhost:4600/project/

###
#get single project
get  http://localhost:4600/project/singleProject
Content-Type: application/json

{
   
    "AssignedUserEmail":"mikvenu9@gmail.com"
   
}

###
#update completed project
post http://localhost:4600/project/updateProject
Content-Type: application/json

{
   
    "projectID":"ba736ff8-a0e5-4188-be1b-897e70636ec3"
   
}

###
#fetch All Users

get http://localhost:4600/project/getUsers





