###
post http://localhost:4600/user/register
Content-Type: application/json

{
    "userName":"Sandra Chege",
    "email":"sandra.chege@thejitu.com",
    "password":"385226",
    "phone_no":"0703142444"
}


###
#login user
POST http://localhost:4600/user/login
Content-Type: application/json

{
    "email":"sandra.chege@thejitu.com",
    "password":"385226"

}


###
#get all user

get http://localhost:4600/user/
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI5MmNhNThjZC1mNTEwLTRhZTYtYjBmNC0zNGE3NDExNTczYmMiLCJ1c2VyTmFtZSI6IlNhbmRyYSBDaGVnZSIsImVtYWlsIjoic2FuZHJhLmNoZWdlQHRoZWppdHUuY29tIiwiaXNBZG1pbiI6ZmFsc2UsIkFzc2lnbmVkUHJvamVjdElEIjpudWxsLCJFbWFpbFNlbnQiOmZhbHNlLCJyb2xlIjoiZW1wbG95ZWUiLCJpYXQiOjE2OTg4NDkxNzgsImV4cCI6MTY5ODg1Mjc3OH0.4FzO7PpVhg6GBdD3JeHFqLIJgRIJUNbJQF7jfFmDUlU


###
#admin asign project
post http://localhost:4600/user/assignProject
Content-Type: application/json

{
    
}